/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalsproject;

import java.awt.event.KeyEvent;
import java.text.Format;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Database.ConnectDB;
import java.sql.*;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author PlonGaming
 */
public class Add_studs extends javax.swing.JFrame {

    /**
     * Creates new form Summary_View
     */
    public Add_studs() {
        initComponents();
        setStudentTable();
        Clear();
        lblID.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        cbGender = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtCourse = new javax.swing.JTextField();
        txtIDnumber = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        ChaAcc = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        cbSem = new javax.swing.JComboBox<>();
        txtComprog = new javax.swing.JTextField();
        txtHci = new javax.swing.JTextField();
        txtArts = new javax.swing.JTextField();
        txtRead = new javax.swing.JTextField();
        txtOtik = new javax.swing.JTextField();
        txtMath = new javax.swing.JTextField();
        txtGpa = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSum = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STUDENT INFORMATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Couture", 1, 16))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Fullname");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Address");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Age");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Civil Status");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Course");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel25.setText("ID number");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Gender");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));
        jPanel2.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 109, 75, 30));

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Single", "Married" }));
        jPanel2.add(cbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 140, 30));

        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Male", "Female", "LGBT" }));
        jPanel2.add(cbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 100, 30));

        txtName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 140, 30));

        txtAge.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel2.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 140, 30));

        txtAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 140, 30));

        txtCourse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(txtCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 100, 30));

        txtIDnumber.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(txtIDnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 100, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACADEMIC GRADES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Couture", 1, 16))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setText("SEMESTER:");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Course Code");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Subject");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setText("Grade");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setText("ITC 102");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setText("COMPUTER PROGRAMMING 2");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel14.setText("ITP 100");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setText("HUMAN-COMPUTER INTERACTION");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setText("HUM 10");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setText("ARTS APPRECIATION");

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel18.setText("HIST 11");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel19.setText("READINGS IN THE PHILIPPINE HISTORY");

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel20.setText("HIST 10");

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel21.setText("MATH 116");

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel22.setText("LIFE AND WORKS OF RIZAL");

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel23.setText("DISCREET MATH FOR IT");

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel24.setText("GRADE POINT AVERAGE");

        Save.setFont(new java.awt.Font("COUTURE", 1, 14)); // NOI18N
        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalsproject/Add_studs.png"))); // NOI18N
        Save.setText("SAVE");
        Save.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        ChaAcc.setFont(new java.awt.Font("COUTURE", 0, 14)); // NOI18N
        ChaAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalsproject/change.png"))); // NOI18N
        ChaAcc.setText("CHANGE ACCOUNT");
        ChaAcc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ChaAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChaAccActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("COUTURE", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalsproject/clearsmall.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        cbSem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "First", "Second" }));

        txtComprog.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtComprog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtComprogKeyReleased(evt);
            }
        });

        txtHci.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtHci.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHciKeyReleased(evt);
            }
        });

        txtArts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtArts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtArtsKeyReleased(evt);
            }
        });

        txtRead.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtRead.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtReadKeyReleased(evt);
            }
        });

        txtOtik.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtOtik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOtikKeyReleased(evt);
            }
        });

        txtMath.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtMath.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMathKeyReleased(evt);
            }
        });

        txtGpa.setEditable(false);
        txtGpa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtGpa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGpaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(ChaAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel12)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(cbSem, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel13)))
                                .addGap(53, 53, 53))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel24))
                                        .addGap(78, 78, 78))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(12, 12, 12))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel15))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtComprog, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtHci, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArts, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOtik, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGpa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRead, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMath, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtComprog, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(txtHci, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(txtArts, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(txtRead, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22)
                    .addComponent(txtOtik, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(txtMath, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtGpa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChaAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 153, 0));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tblSum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID NUMBER", "FULLNAME", "AGE", "ADDRESS", "GENDER", "GPA", "SEMESTER", "CIVIL STATUS", "COURSE", "ITC 102", "ITP 100", "MATH 116", "HUM 10", "HIST 10", "HIST 11"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSumMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSum);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 153, 0));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnUpdate.setFont(new java.awt.Font("COUTURE", 1, 16)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalsproject/Update.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDel.setFont(new java.awt.Font("COUTURE", 1, 16)); // NOI18N
        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalsproject/Delete.png"))); // NOI18N
        btnDel.setText("DELETE");
        btnDel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btnDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 153, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Couture", 1, 16)); // NOI18N
        jLabel2.setText("SEARCH STUDENT BY ID NUMBER");

        Search.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        Search.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                SearchPropertyChange(evt);
            }
        });
        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchKeyPressed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Couture", 1, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalsproject/searchSmall.png"))); // NOI18N
        btnSearch.setText("SEARCH!");
        btnSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        btnSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSearchKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChaAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChaAccActionPerformed
        int res = JOptionPane.showConfirmDialog(null, "You are about to change your account!", "Student Academic Overview", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (res == JOptionPane.YES_OPTION) {
            dispose();
            LogIn_frame log = new LogIn_frame();
            log.setVisible(true);
        } else if (res == JOptionPane.NO_OPTION) {

        }
    }//GEN-LAST:event_ChaAccActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed

        if (txtName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "There is NOTHING to SAVE!", "Student Academic Overview", JOptionPane.WARNING_MESSAGE);
        } else {
            if (!txtName.getText().equals("")) {
                Addstudent();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid User Input!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_SaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        Clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed

        int reply = JOptionPane.showConfirmDialog(null, "Do you wish to DELETE this Student?","Student Academic Overview", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if (reply == JOptionPane.YES_OPTION){
        if (txtName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "There is Nothing to DELETE!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                int id = Integer.parseInt(lblID.getText());
                Delete(id);
                Clear();
                setStudentTable();
            } catch (SQLException ex) {
                Logger.getLogger(Add_studs.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }else if (reply == JOptionPane.NO_OPTION){
            
        }

    }//GEN-LAST:event_btnDelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
//        DefaultTableModel model = (DefaultTableModel) tblSum.getModel();
//        if (tblSum.getSelectedRow() == -1) {
//            if (tblSum.getRowCount() == 0) {
//                JOptionPane.showMessageDialog(null, "Table is EMPTY!", "ERROR!", JOptionPane.ERROR_MESSAGE);
//            } else {
//                JOptionPane.showMessageDialog(null, "Please Select a Product!", "Warning!", JOptionPane.WARNING_MESSAGE);
//            }
//        } else {
//            int fname = Integer.parseInt(txtfullname.getText());
//            UpdateStudent(fname);
//        }

        if (txtName.getText().trim().isEmpty() || txtAge.getText().trim().isEmpty() || txtAddress.getText().trim().isEmpty()
                || txtCourse.getText().trim().isEmpty() || cbStatus.getSelectedItem().equals("") || txtIDnumber.getText().trim().isEmpty() || cbGender.getSelectedItem().equals("") || cbSem.getSelectedItem().equals("")
                || txtComprog.getText().trim().isEmpty() || txtHci.getText().trim().isEmpty() || txtMath.getText().trim().isEmpty()
                || txtArts.getText().trim().isEmpty() || txtOtik.getText().trim().isEmpty() || txtRead.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "There are fields that is EMPTY!", "Error!", JOptionPane.WARNING_MESSAGE);
        } else {

            if (lblID.getText().equals("")) {
                Addstudent();
            } else {
                int wew = Integer.parseInt(lblID.getText());
                UpdateStudent(wew);
                Clear();
            }
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblSumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSumMouseClicked
        int sel = tblSum.getSelectedRow();
        lblID.setText(tblSum.getValueAt(sel, 0).toString());
        txtIDnumber.setText(tblSum.getValueAt(sel, 1).toString());
        txtName.setText(tblSum.getValueAt(sel, 2).toString());
        txtAge.setText(tblSum.getValueAt(sel, 3).toString());
        cbStatus.setSelectedItem(tblSum.getValueAt(sel, 4).toString());
        txtAddress.setText(tblSum.getValueAt(sel, 5).toString());
        cbGender.setSelectedItem(tblSum.getValueAt(sel, 6).toString());
        cbSem.setSelectedItem(tblSum.getValueAt(sel, 7).toString());
        txtCourse.setText(tblSum.getValueAt(sel, 8).toString());
        txtComprog.setText(tblSum.getValueAt(sel, 10).toString());
        txtHci.setText(tblSum.getValueAt(sel, 9).toString());
        txtMath.setText(tblSum.getValueAt(sel, 11).toString());
        txtOtik.setText(tblSum.getValueAt(sel, 12).toString());
        txtArts.setText(tblSum.getValueAt(sel, 13).toString());
        txtRead.setText(tblSum.getValueAt(sel, 14).toString());
        txtGpa.setText(tblSum.getValueAt(sel, 15).toString());
        lblID.setVisible(false);

    }//GEN-LAST:event_tblSumMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        setStudentTable();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void SearchPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_SearchPropertyChange
        setStudentTable();
        System.out.println("There is an error!");
    }//GEN-LAST:event_SearchPropertyChange

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void txtGpaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGpaKeyReleased

    }//GEN-LAST:event_txtGpaKeyReleased

    private void txtMathKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMathKeyReleased
        Compute();
    }//GEN-LAST:event_txtMathKeyReleased

    private void txtOtikKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOtikKeyReleased
        Compute();
    }//GEN-LAST:event_txtOtikKeyReleased

    private void txtReadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReadKeyReleased

        Compute();
    }//GEN-LAST:event_txtReadKeyReleased

    private void txtArtsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArtsKeyReleased

        Compute();
    }//GEN-LAST:event_txtArtsKeyReleased

    private void txtHciKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHciKeyReleased
        Compute();
    }//GEN-LAST:event_txtHciKeyReleased

    private void btnSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSearchKeyPressed

    }//GEN-LAST:event_btnSearchKeyPressed

    private void SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            setStudentTable();
        }
    }//GEN-LAST:event_SearchKeyPressed

    private void txtComprogKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComprogKeyReleased
        Compute();
    }//GEN-LAST:event_txtComprogKeyReleased

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Add_studs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Add_studs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Add_studs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Add_studs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Add_studs().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChaAcc;
    private javax.swing.JButton Save;
    private javax.swing.JTextField Search;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JComboBox<String> cbSem;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JTable tblSum;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtArts;
    private javax.swing.JTextField txtComprog;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtGpa;
    private javax.swing.JTextField txtHci;
    private javax.swing.JTextField txtIDnumber;
    private javax.swing.JTextField txtMath;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOtik;
    private javax.swing.JTextField txtRead;
    // End of variables declaration//GEN-END:variables

    public void Clear() {
        lblID.setText(null);
        txtName.setText(null);
        txtAddress.setText(null);
        txtAge.setText(null);
        cbStatus.setSelectedItem(null);
        txtIDnumber.setText(null);
        txtCourse.setText(null);
        cbGender.setSelectedItem(null);
        cbSem.setSelectedItem(null);
        txtComprog.setText(null);
        txtHci.setText(null);
        txtArts.setText(null);
        txtGpa.setText(null);
        txtRead.setText(null);
        txtOtik.setText(null);
        txtMath.setText(null);
    }

//    public void ifisEmpty() {
//        if (txtName.getText().trim().isEmpty() || txtAge.getText().trim().isEmpty() || txtAddress.getText().trim().isEmpty()
//                || txtCourse.getText().trim().isEmpty() || cbStatus.getSelectedItem().equals("") || txtIDnumber.getText().trim().isEmpty() || cbGender.getSelectedItem().equals("") || cbSem.getSelectedItem().equals("")
//                || txtComprog.getText().trim().isEmpty() || txtHci.getText().trim().isEmpty() || txtMath.getText().trim().isEmpty()
//                || txtArts.getText().trim().isEmpty() || txtOtik.getText().trim().isEmpty() || txtRead.getText().trim().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "There are fields that is EMPTY!", "Error!", JOptionPane.ERROR_MESSAGE);
//        } 
//        else {
//            DefaultTableModel model = (DefaultTableModel) tblSum.getModel();
//            if (!txtName.getText().trim().equals("")) {
//                model.addRow(new Object[]{txtIDnumber.getText(), txtName.getText(), txtAge.getText(), cbStatus.getSelectedItem().toString(), txtAddress.getText(),
//                    cbGender.getSelectedItem().toString(), cbSem.getSelectedItem().toString(), txtCourse.getText(), txtComprog.getText(), txtHci.getText(), txtMath.getText(),
//                    txtOtik.getText(), txtArts.getText(), txtRead.getText(), txtGpa.getText()});
//            }
//      }
//
//    }
    public void Addstudent() {
        String fname = txtName.getText();
        String age = txtAge.getText();
        String address = txtAddress.getText();
        String status = cbStatus.getSelectedItem().toString();
        String course = txtCourse.getText();
        String idnum = txtIDnumber.getText();
        String gender = cbGender.getSelectedItem().toString();
        String semester = cbSem.getSelectedItem().toString();
        String comprog = txtComprog.getText();
        String hci = txtHci.getText();
        String math = txtMath.getText();
        String arts = txtArts.getText();
        String otik = txtOtik.getText();
        String read = txtRead.getText();
        String gpa = txtGpa.getText();

        String query = "INSERT INTO `students`(`id`, `Idnumber`, `Fname`, `Age`, `Address`, `Gender`, `Course`, `Civilstats`, `Sem`, `Comprog`, `Hci`, `Math`, `Arts`, `Hist10`, `Hist11`, `Gpa`)"
                + "VALUES (NULL, '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s');";

        query = String.format(query, idnum, fname, age, address, gender, course, status, semester, comprog, hci, math, arts, otik, read, gpa);

        try {
            ConnectDB.Query(query, true);
            setStudentTable();
            Clear();
            JOptionPane.showMessageDialog(null, "Successfully Added!", "Student Academic Overview", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            Logger.getLogger(Add_studs.class.getName()).log(Level.SEVERE, null, e);
        }

    }

    public void setStudentTable() {
        try {
            String search = Search.getText();
            String[][] datas = Addstudents.Arraylist(Addstudents.searchStudentUsingId(search));
            String[] ColNames = {"id", "ID number", "Fullname", "Age", "Status", "Address", "Gender", "Sem", "Course", "Comprog", "HCI", "Math", "Arts", "Hist10", "Hist11", "Gpa"};

            DefaultTableModel dtm = new DefaultTableModel(datas, ColNames);
            tblSum.setModel(dtm);
            TableColumnModel Col = tblSum.getColumnModel();
            tblSum.setColumnModel(Col);
        } catch (SQLException e) {
            Logger.getLogger(Add_studs.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    public void UpdateStudent(int id) {

        String Idnumber = txtIDnumber.getText();
        String fname = txtName.getText();
        String age = txtAge.getText();
        String status = cbStatus.getSelectedItem().toString();
        String address = txtAddress.getText();
        String gender = cbGender.getSelectedItem().toString();
        String sem = cbSem.getSelectedItem().toString();
        String course = txtCourse.getText();
        String comprog = txtComprog.getText();
        String hci = txtHci.getText();
        String math = txtMath.getText();
        String arts = txtArts.getText();
        String otik = txtOtik.getText();
        String read = txtRead.getText();
        String gpa = txtGpa.getText();

        String update = "UPDATE `students` SET `Idnumber`= '%s',`Fname`= '%s',`Age`= '%s', `Address`= '%s', `Course`= '%s', "
                + "`Gender`= '%s',`Civilstats`= '%s',`Sem`= '%s',`Comprog`= '%s',`Hci`= '%s',"
                + "`Math`= '%s',`Arts`= '%s',`Hist10`= '%s',`Hist11`='%s',`Gpa`= '%s' WHERE `students`.`id` = '%d';";

        update = String.format(update, Idnumber, fname, age, address, course, gender, status, sem, comprog, hci, math, arts, otik, read, gpa, id);

        try {
            ConnectDB.Query(update, true);
            setStudentTable();
            JOptionPane.showMessageDialog(null, "Update Successfully Executed!", "Student Academic Overview", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            Logger.getLogger(Add_studs.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    public void Delete(int Id) throws SQLException {

        String query = "DELETE FROM `students` WHERE `students`.`id` = %d";

        query = String.format(query, Id);

        try {
            ConnectDB.Query(query, true);
            JOptionPane.showMessageDialog(null, "Done!", "Student Academic Overview", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            Logger.getLogger(Add_studs.class.getName()).log(Level.SEVERE, null, e);
        }
        setStudentTable();
        Clear();
    }

    public void Compute() {
        float Prograde = Float.parseFloat(txtComprog.getText());
        float hci = Float.parseFloat(txtHci.getText());
        float Math = Float.parseFloat(txtMath.getText());
        float hist11 = Float.parseFloat(txtRead.getText());
        float hist10 = Float.parseFloat(txtOtik.getText());
        float Arts = Float.parseFloat(txtArts.getText());

        float IntGrade = Prograde + hci + Math + Arts + hist10 + hist11;
        float FinGrade = IntGrade / 6;

        String result = String.valueOf(FinGrade);

        txtGpa.setText(result);
    }

}
