/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalsproject;

import java.awt.event.KeyEvent;
import javafx.scene.control.ButtonBar;
import javax.swing.JOptionPane;

/**
 *
 * @author PlonGaming
 */
public class Front_Page extends javax.swing.JFrame {

    private String username;
   
    /**
     * Creates new form Front_Page
     * @param Username
     */
    public Front_Page(String Username) {
        this.username = Username;
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Add_Stud = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add_Stud.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Add_Stud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalsproject/add-userSmall.png"))); // NOI18N
        Add_Stud.setText("ADD STUDENT");
        Add_Stud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_StudActionPerformed(evt);
            }
        });
        Add_Stud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Add_StudKeyPressed(evt);
            }
        });
        getContentPane().add(Add_Stud, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 170, 50));

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalsproject/Logout.png"))); // NOI18N
        jButton1.setText("LOG-OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 180, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalsproject/Front cover v2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_StudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_StudActionPerformed
        dispose();
        Add_studs a = new Add_studs();
        a.setVisible(true);
    }//GEN-LAST:event_Add_StudActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Do you want to Log-out?", "Student Academic Overview", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (reply == JOptionPane.YES_OPTION) {
            dispose();
            LogIn_frame log = new LogIn_frame();
            log.setVisible(true);
        } else if (reply == JOptionPane.NO_OPTION) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Add_StudKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Add_StudKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Add_studs a = new Add_studs();
            a.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_Add_StudKeyPressed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Front_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Front_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Front_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Front_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Front_Page().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Stud;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
